/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../components/setting/components/about.vue')['default']
    AgentConfig: typeof import('./../components/setting/components/agentConfig.vue')['default']
    AudioUploadBox: typeof import('./../components/setting/components/vendorTest/AudioUploadBox.vue')['default']
    ContextMenu: typeof import('./../components/edit/contextMenu.vue')['default']
    DbConfig: typeof import('./../components/setting/components/dbConfig.vue')['default']
    DevConfig: typeof import('./../components/setting/components/devConfig.vue')['default']
    Edge: typeof import('./../components/edit/edge.vue')['default']
    Edit: typeof import('./../components/edit/index.vue')['default']
    EditMdPreview: typeof import('./../components/editMdPreview.vue')['default']
    FileManagement: typeof import('./../components/setting/components/fileManagement.vue')['default']
    Hello: typeof import('./../components/hello.vue')['default']
    ImageModelTest: typeof import('./../components/setting/components/vendorTest/ImageModelTest.vue')['default']
    ImageTools: typeof import('./../components/imageTools.vue')['default']
    ImageUploadBox: typeof import('./../components/setting/components/vendorTest/ImageUploadBox.vue')['default']
    LanguageConfig: typeof import('./../components/setting/components/languageConfig.vue')['default']
    LoginConfig: typeof import('./../components/setting/components/loginConfig.vue')['default']
    LogoutConfig: typeof import('./../components/setting/components/logoutConfig.vue')['default']
    MemoryConfig: typeof import('./../components/setting/components/memoryConfig.vue')['default']
    ModelMap: typeof import('./../components/setting/components/modelMap.vue')['default']
    ModelSelect: typeof import('./../components/modelSelect.vue')['default']
    OtherConfig: typeof import('./../components/setting/components/otherConfig.vue')['default']
    PluginConfig: typeof import('./../components/setting/components/pluginConfig.vue')['default']
    PluginNode: typeof import('./../components/edit/pluginNode.vue')['default']
    PromptEditor: typeof import('./../components/promptEditor.vue')['default']
    PromptManage: typeof import('./../components/setting/components/promptManage.vue')['default']
    RequestConfig: typeof import('./../components/setting/components/requestConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./../components/setting/index.vue')['default']
    SkillManagement: typeof import('./../components/setting/components/skillManagement.vue')['default']
    StoryboardImageCheck: typeof import('./../components/storyboardImageCheck.vue')['default']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TextModelTest: typeof import('./../components/setting/components/vendorTest/TextModelTest.vue')['default']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    UiConfig: typeof import('./../components/setting/components/uiConfig.vue')['default']
    VendorConfig: typeof import('./../components/setting/components/vendorConfig.vue')['default']
    VideoModelTest: typeof import('./../components/setting/components/vendorTest/VideoModelTest.vue')['default']
    VideoUploadBox: typeof import('./../components/setting/components/vendorTest/VideoUploadBox.vue')['default']
  }
}
